// <auto-generated />
namespace Edulu3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Create_TraviasTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_TraviasTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202112141210222_Create_TraviasTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
